steps:
  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - live
    env:
      APP_SECRET: prod
      DOCKERFILE_BUILD_STEP: artifact

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - release
    env:
      APP_SECRET: release
      DOCKERFILE_BUILD_STEP: artifact

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - main
    env:
      APP_SECRET: stage
      DOCKERFILE_BUILD_STEP: artifact-storybook

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - "!live"
      - "!release"
      - "!main"
    env:
      APP_SECRET: dev
      DOCKERFILE_BUILD_STEP: artifact-storybook
