#!/bin/sh

## Description: Run nextjs commands to rebuild the app
## Usage: nextjs install|build|deploy|watch|(some other command in the theme service)
## Example: "ddev nextjs build"

case $1 in
  install)
    npm ci
  ;;
  build)
    npm run build
  ;;
  restart)
    pm2 restart $2
  ;;
  monit)
    pm2 monit
  ;;
  run)
    npm run dev
  ;;
  "")
    echo "Usage: nextjs install|build|deploy|watch|(some other command in the theme service)"
  ;;
  *)
    "$@"
  ;;
esac